required = [
  "github.com/alvaroloes/enumer",
  "github.com/jim-minter/go-cosmosdb/cmd/gencosmosdb",
  "github.com/golang/mock/mockgen",
  "github.com/go-bindata/go-bindata/go-bindata",
  "golang.org/x/tools/cmd/goimports",
  "github.com/jstemmer/go-junit-report",
  "github.com/axw/gocov/gocov",
  "github.com/AlekSi/gocov-xml",
  "github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/gengo/generator",
  "sigs.k8s.io/controller-tools/cmd/controller-gen",
]

[[constraint]]
  name = "github.com/alvaroloes/enumer"
  version = "1.1.2"

[[override]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "40.2.0"

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.16.0-beta.0"

[[override]]
  name = "sigs.k8s.io/controller-tools"
  version = "v0.2.5"

[[constraint]]
  name = "k8s.io/gengo"
  revision = "f8a0810f38afb8478882b3835a615aebfda39afa"

[[override]]
  name = "github.com/containers/image"
  version = "v2.0.1"

[[constraint]]
  name = "github.com/golang/mock"
  version = "1.3.1"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.7.3"

[[constraint]]
  name = "github.com/openshift/api"
  branch = "release-4.3"

[[constraint]]
  name = "github.com/openshift/client-go"
  branch = "release-4.3"

[[override]]
  name = "github.com/openshift/cluster-api"
  branch = "release-4.3"

[[override]]
  name = "github.com/openshift/cluster-samples-operator"
  branch = "release-4.3"

[[constraint]]
  name = "github.com/openshift/cluster-api-provider-azure"
  branch = "release-4.3"

[[override]]
  name = "sigs.k8s.io/controller-runtime"
  branch = "release-0.5"

[[constraint]]
  name = "github.com/openshift/installer"
  branch = "release-4.3-azure"
  source = "https://github.com/jim-minter/installer"

[[override]]
  name = "github.com/openshift/machine-config-operator"
  branch = "release-4.3"

[[constraint]]
  name = "github.com/openshift/console-operator"
  branch = "release-4.3"

[[constraint]]
  name = "github.com/coreos/prometheus-operator"
  branch = "release-0.38"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[constraint]]
  name = "github.com/ugorji/go"
  version = "1.1.7"

[[constraint]]
  name = "golang.org/x/crypto"
  branch = "master"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  branch = "release-1.17"

[[override]]
  name = "k8s.io/api"
  branch = "origin-4.3-kubernetes-1.16.2"
  source = "https://github.com/openshift/kubernetes-api"

[[override]]
  name = "k8s.io/apimachinery"
  branch = "origin-4.3-kubernetes-1.16.2"
  source = "https://github.com/openshift/kubernetes-apimachinery"

[[override]]
  name = "k8s.io/client-go"
  branch = "origin-4.3-kubernetes-1.16.2"
  source = "https://github.com/openshift/kubernetes-client-go"

[[override]]
  name = "sigs.k8s.io/cluster-api-provider-azure"
  branch = "release-4.3"
  source = "https://github.com/openshift/cluster-api-provider-azure"

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"

[prune]
  go-tests = true
  unused-packages = true

  [[prune.project]]
    name = "github.com/openshift/installer"
    unused-packages = false
