required = ["github.com/jim-minter/go-cosmosdb/cmd/gencosmosdb", "github.com/alvaroloes/enumer"]

[[override]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "36.2.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.7.3"

[[constraint]]
  name = "github.com/openshift/api"
  branch = "release-4.3"

[[constraint]]
  name = "github.com/openshift/client-go"
  branch = "release-4.3"

[[override]]
  name = "github.com/openshift/cluster-api"
  branch = "release-4.3"

[[constraint]]
  name = "github.com/openshift/installer"
  branch = "release-4.3-azure"
  source = "https://github.com/jim-minter/installer"

[[override]]
  name = "github.com/openshift/machine-config-operator"
  branch = "release-4.3"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[constraint]]
  name = "github.com/ugorji/go"
  version = "1.1.7"

[[override]]
  name = "k8s.io/api"
  branch = "origin-4.3-kubernetes-1.16.2"
  source = "https://github.com/openshift/kubernetes-api"

[[override]]
  name = "k8s.io/apimachinery"
  branch = "origin-4.3-kubernetes-1.16.2"
  source = "https://github.com/openshift/kubernetes-apimachinery"

[[override]]
  name = "k8s.io/client-go"
  branch = "origin-4.3-kubernetes-1.16.2"
  source = "https://github.com/openshift/kubernetes-client-go"

[[override]]
  name = "sigs.k8s.io/cluster-api-provider-azure"
  branch = "release-4.3"
  source = "https://github.com/openshift/cluster-api-provider-azure"

[[constraint]]
  name = "github.com/jim-minter/go-cosmosdb"
  branch = "master"

[[constraint]]
  name = "github.com/alvaroloes/enumer"
  version = "1.1.2"

[prune]
  go-tests = true
  unused-packages = true

  [[prune.project]]
    name = "github.com/openshift/installer"
    unused-packages = false
