apiVersion: v1
kind: ConfigMap
metadata:
  name: managed-upgrade-operator-config
  namespace: openshift-managed-upgrade-operator
data:
  config.yaml: |
    upgradeType: ARO
    configManager:
      source: {{ if .EnableConnected }}OCM{{ else }}LOCAL{{ end }}
      {{ if .EnableConnected }}ocmBaseUrl: {{.OCMBaseURL}}{{end}}
      {{ if not .EnableConnected }}localConfigName: managed-upgrade-config{{end}}
      watchInterval: {{ if .EnableConnected }}60{{ else }}15{{ end }}
    maintenance:
      controlPlaneTime: 90
      ignoredAlerts:
        controlPlaneCriticals:
        - ClusterOperatorDown
        - ClusterOperatorDegraded
    upgradeWindow:
      delayTrigger: 30
      timeOut: 120
    nodeDrain:
      timeOut: 45
      expectedNodeDrainTime: 8
    scale:
      timeOut: 30
    healthCheck:
      ignoredCriticals:
      - PrometheusRuleFailures
      - CannotRetrieveUpdates
      - FluentdNodeDown
      ignoredNamespaces:
      - openshift-logging
      - openshift-redhat-marketplace
      - openshift-operators
      - openshift-user-workload-monitoring
      - openshift-pipelines
      - openshift-azure-logging
