apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aro-operator-worker
  name: aro-operator-worker
  namespace: openshift-azure-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aro-operator-worker
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: aro-operator-worker
    spec:
      containers:
      - command:
        - aro
        args:
        - operator
        - worker
        image: GENERATED
        name: aro-operator
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      serviceAccountName: aro-operator-worker
      priorityClassName: system-cluster-critical
