name: ci-go

on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  ci-from-docker:
    runs-on: ubuntu-latest
    container:
      image: registry.access.redhat.com/ubi8/go-toolset:1.20.10
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install Go runtime deps
      run: |
        make install-go-tools
    - name: Build all
      run: |
        make build-all
    - name: Run unit tests
      run: |
        make unit-test-go

  vendor-check:
    runs-on: ubuntu-latest
    container:
      image: registry.access.redhat.com/ubi8/go-toolset:1.20.10
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - run: |
        make go-verify
        hack/ci-utils/isClean.sh

  generate-check:
    runs-on: ubuntu-latest
    container:
      image: registry.access.redhat.com/ubi8/go-toolset:1.20.10
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Run make generate
      run: |
        make generate
        hack/ci-utils/isClean.sh
