name: ci-go

on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
permissions:
  contents: read

jobs:
  ci-from-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: build from buildah
        uses: redhat-actions/buildah-build@v2
        with:
          image: test-image
          tags: ${{ github.sha }}
          context: .
          containerfiles: ./Dockerfile.ci
  vendor-check:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install libgpgme-dev libgpgme11
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - run: |
          go mod vendor
          go mod tidy -compat=1.18
          hack/ci-utils/isClean.sh
