name: pull_request-test-python
on:
  pull_request:
    types:
    - opened
    - synchronize
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/work/ARO-RP/go
    strategy:
      matrix:
        python-version:
        - 2.7
        - 3.5.7
        - 3.6.9
        - 3.7.5
        - 3.8.0
    steps:
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - name: Check out source
      uses: actions/checkout@v1
      with:
        path: go/src/github.com/Azure/ARO-RP
    - name: Test
      run: |
        set -x
        pip install virtualenv
        make test-python
